import type { Vehicle, Journey, Friend, Convoy, Destination, Achievement } from '@/context/AppContext';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'mock-vehicle-1',
    nickname: 'The Green Monster',
    registration: 'AB12CDE',
    make: 'MINI',
    model: 'Cooper R50',
    year: 2003,
    colour: 'British Racing Green',
    fuelType: 'petrol',
    engine: '1.6L',
    power: '115 bhp',
    torque: '149 Nm',
    zeroToSixty: '10.9s',
    topSpeed: '120 mph',
    mileage: 96512,
    fuelPercentage: 62,
    imageUri: null,
    isActive: true,
  },
  {
    id: 'mock-vehicle-2',
    nickname: 'Daily Driver',
    registration: 'YD19XKL',
    make: 'BMW',
    model: '3 Series 320d',
    year: 2019,
    colour: 'Alpine White',
    fuelType: 'diesel',
    engine: '2.0L',
    power: '190 bhp',
    torque: '400 Nm',
    zeroToSixty: '6.8s',
    topSpeed: '155 mph',
    mileage: 42300,
    fuelPercentage: 85,
    imageUri: null,
    isActive: false,
  },
];

export const MOCK_JOURNEYS: Journey[] = [
  {
    id: 'journey-1',
    name: 'Lake District Loop',
    date: '2026-07-19',
    startTime: '09:15',
    endTime: '12:47',
    duration: 12720,
    distance: 87.4,
    averageSpeed: 52,
    topSpeed: 78,
    vehicleId: 'mock-vehicle-1',
    notes: 'Perfect conditions, stopped at Grasmere for coffee.',
    routeCoordinates: [
      { latitude: 54.4609, longitude: -3.0886 },
      { latitude: 54.4800, longitude: -3.1200 },
      { latitude: 54.5100, longitude: -3.1500 },
    ],
    photos: [],
  },
  {
    id: 'journey-2',
    name: 'Morning Commute',
    date: '2026-07-18',
    startTime: '08:02',
    endTime: '08:34',
    duration: 1920,
    distance: 14.2,
    averageSpeed: 27,
    topSpeed: 56,
    vehicleId: 'mock-vehicle-2',
    notes: '',
    routeCoordinates: [
      { latitude: 54.4609, longitude: -3.0886 },
      { latitude: 54.4700, longitude: -3.0700 },
    ],
    photos: [],
  },
  {
    id: 'journey-3',
    name: 'B5289 Blast',
    date: '2026-07-15',
    startTime: '16:30',
    endTime: '18:10',
    duration: 6000,
    distance: 63.8,
    averageSpeed: 60,
    topSpeed: 85,
    vehicleId: 'mock-vehicle-1',
    notes: 'Incredible driving road through Honister Pass.',
    routeCoordinates: [
      { latitude: 54.5200, longitude: -3.1600 },
      { latitude: 54.5400, longitude: -3.2000 },
      { latitude: 54.5600, longitude: -3.2400 },
    ],
    photos: [],
  },
  {
    id: 'journey-4',
    name: 'Peak District Weekend',
    date: '2026-07-12',
    startTime: '07:45',
    endTime: '13:20',
    duration: 20100,
    distance: 142.5,
    averageSpeed: 51,
    topSpeed: 82,
    vehicleId: 'mock-vehicle-1',
    notes: 'Overnight trip, stunning Snake Pass in the morning fog.',
    routeCoordinates: [
      { latitude: 54.4609, longitude: -3.0886 },
      { latitude: 53.4200, longitude: -1.7500 },
    ],
    photos: [],
  },
];

export const MOCK_FRIENDS: Friend[] = [
  { id: 'friend-1', name: 'Sarah T.', initials: 'ST', status: 'driving', location: 'M6 Northbound' },
  { id: 'friend-2', name: 'James H.', initials: 'JH', status: 'online', location: 'Manchester' },
  { id: 'friend-3', name: 'Emma K.', initials: 'EK', status: 'offline', location: '' },
  { id: 'friend-4', name: 'Mike R.', initials: 'MR', status: 'driving', location: 'A66' },
  { id: 'friend-5', name: 'Priya N.', initials: 'PN', status: 'online', location: 'Leeds' },
];

export const MOCK_CONVOYS: Convoy[] = [
  {
    id: 'convoy-1',
    name: 'Sunday Scenic Run',
    leaderId: 'friend-1',
    leaderName: 'Sarah T.',
    destination: 'Kirkstone Pass Inn',
    driverCount: 6,
    isPrivate: false,
    startTime: '2026-07-26T10:00:00',
    status: 'forming',
    description: 'Classic B-road loop via Kirkstone and Ullswater.',
  },
  {
    id: 'convoy-2',
    name: 'Track Day Convoy',
    leaderId: 'friend-4',
    leaderName: 'Mike R.',
    destination: 'Croft Circuit',
    driverCount: 4,
    isPrivate: true,
    startTime: '2026-07-28T07:30:00',
    status: 'forming',
    description: 'Heading to Croft for track day. Invitation only.',
  },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  { id: 'ach-1', title: 'First Drive', description: 'Completed your first tracked journey', icon: 'flag-outline', unlockedAt: '2026-06-01' },
  { id: 'ach-2', title: 'Century Run', description: 'Drove 100km in a single journey', icon: 'speedometer-outline', unlockedAt: '2026-06-15' },
  { id: 'ach-3', title: 'Early Bird', description: 'Started a drive before 7am', icon: 'sunny-outline', unlockedAt: '2026-07-12' },
  { id: 'ach-4', title: 'Road Warrior', description: 'Drive 1,000km total', icon: 'trophy-outline', unlockedAt: '2026-07-18' },
  { id: 'ach-5', title: 'Convoy Leader', description: 'Lead your first convoy', icon: 'people-outline', unlockedAt: null },
  { id: 'ach-6', title: 'Mountain Road', description: 'Drive over 600m elevation', icon: 'triangle-outline', unlockedAt: null },
];

export const DEMO_DESTINATIONS: Destination[] = [
  { id: 'dest-home', name: 'Home', address: '14 Lakeside Drive, Keswick CA12 5DQ', type: 'home', coordinate: { latitude: 54.4609, longitude: -3.0886 } },
  { id: 'dest-work', name: 'Work', address: 'The Innovation Hub, Carlisle CA1 1JX', type: 'work', coordinate: { latitude: 54.8924, longitude: -2.9328 } },
  { id: 'dest-1', name: 'Kirkstone Pass Inn', address: 'Kirkstone Pass, Ambleside LA22 9LQ', type: 'scenic', coordinate: { latitude: 54.4846, longitude: -2.9167 } },
  { id: 'dest-2', name: 'Honister Pass', address: 'Honister, Keswick CA12 5XN', type: 'scenic', coordinate: { latitude: 54.5167, longitude: -3.2000 } },
  { id: 'dest-3', name: 'Grasmere Village', address: 'Grasmere, Ambleside LA22 9QL', type: 'favourite', coordinate: { latitude: 54.4608, longitude: -3.0228 } },
  { id: 'dest-4', name: 'Windermere Lake', address: 'Lake Windermere, Cumbria LA23 1JH', type: 'favourite', coordinate: { latitude: 54.3703, longitude: -2.9244 } },
  { id: 'dest-5', name: 'Snake Pass', address: 'A57 Snake Pass, Hope Valley S33', type: 'scenic', coordinate: { latitude: 53.4500, longitude: -1.8167 } },
];

export const SCENIC_ROUTES: { id: string; name: string; distance: string; description: string }[] = [
  { id: 'scenic-1', name: 'Hardknott Pass Loop', distance: '28 km', description: 'England\'s steepest road — dramatic fellside switchbacks' },
  { id: 'scenic-2', name: 'B5289 Borrowdale', distance: '19 km', description: 'Classic valley road alongside Derwent Water' },
  { id: 'scenic-3', name: 'Kirkstone Loop', distance: '42 km', description: 'Via Ullswater and back through Ambleside' },
  { id: 'scenic-4', name: 'North Yorkshire Moors', distance: '88 km', description: 'Open moorland, rolling valleys, perfect on a clear day' },
];
